// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import { config } from "dotenv";

if (fs.existsSync(".env.local")) {
  config({ path: ".env.local" });
} else if (fs.existsSync(".env")) {
  config();
}

import { defineConfig } from "prisma/config";

const datasourceUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;

if (!datasourceUrl) {
  throw new Error("Missing required environment variable: DATABASE_URL (or DIRECT_URL)");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: datasourceUrl,
  },
});
